# -*- coding: utf-8 -*-
"""TWITTER BOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DNghLRicBw9P5R2ZwLi9GlKuhVnB4wWS
"""

import random
print(random.randint(0,4))
print(random.randint(0,4))

part1=["a","b","c","d","q","u"]
part2=["e","f","g","h","r","v"]
part3=["i","j","k","l","s","w"]
part4=["m","n","o","p","t","x"]

#we can create lists from other lists
best_words=[part1,part2,part3,part4]
print(best_words)

sentence=[]
for part in best_words:
  print(len(part))
  r=random.randint(0,len(part)-1)
  print(part[r])
  print(r)
  sentence.append(part[r])
print(sentence)
print(",".join(sentence))

